services:
  - type: web
    name: n8n
    runtime: image
    image: docker.io/n8nio/n8n:latest
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_SECURE_COOKIE
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: GENERIC_TIMEZONE
        value: "America/Sao-Paulo"
      - key: TZ
        value: "America/Sao-Paulo"
      - key: WEBHOOK_URL
        value: "https://n8n-uee1.onrender.com"
      - key: N8N_EDITOR_BASE_URL
        value: "https://n8n-uee1.onrender.com"
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
